# Generated by Django 3.2.6 on 2022-03-04 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=250)),
                ('user_type', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=100)),
                ('blog_title', models.CharField(max_length=200)),
                ('blogContent', djrichtextfield.models.RichTextField()),
                ('blog_image', models.ImageField(upload_to='uploads/')),
                ('blog_date', models.DateField(default=django.utils.timezone.now)),
                ('blogAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.webuser')),
            ],
        ),
    ]
