# Generated by Django 3.2.6 on 2022-03-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_blogposts_blogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
