# Generated by Django 3.2.6 on 2022-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('helpline_no', models.CharField(max_length=1000)),
            ],
        ),
    ]
